### PR TITLE
Lighten icon in dark mode

### PR DESCRIPTION
**Pull request by Quantum-Codes**
- [ ] Currently looks very dark. So apply brightness to `material-design-outline`
- [ ] Also the navbar and main page color aren't very distinguishable in dark mode. Maybe change either
- [x] Remove dev reference from `contributing.md` and `Readme.md`

(First 2 not done as I can't get previews work)

### CODE REVIEW

**Comment by Quantum-Codes** [comment]
How to trigger preview deployment?

**Comment by TurtleCode84** [comment]
> How to trigger preview deployment?

Sorry about that, I locked down preview deployments so they only deploy for my commits, and even then only I can see them because I haven't been using a separate development database, I'll see what I can do

**Comment by TurtleCode84** [comment]
@Quantum-Codes This link should work for the branch: http://tracktask-git-quantum-codes-patch-1-turtlecode84.vercel.app?_vercel_share=oRqacdll8qZ6tVJBajMqLlROVHcEg5eO

**Comment by Quantum-Codes** [comment]
Ty

**Pull request merged**
